version: '3'

services:
  mailhog:
    image: mailhog/mailhog
    container_name: server-lister-mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
