issuer: http://dex:5556/dex
storage:
  type: memory

# LDAP Connector
connectors:
  - type: ldap
    id: ldap
    name: LDAP
    config:
      host: 100.81.55.28:1389 # Your OpenLDAP server
      insecureNoSSL: true # Disable SSL (since you're using LDAP, not LDAPS)
      bindDN: "cn=admin,dc=example,dc=org" # Admin user to bind
      bindPW: "lamb##" # Admin password
      userSearch:
        baseDN: "dc=example,dc=org"
        filter: "(objectClass=inetOrgPerson)"
        username: uid
        idAttr: uid
        emailAttr: mail
        nameAttr: cn
      groupSearch:
        baseDN: "dc=example,dc=org"
        filter: "(objectClass=posixGroup)"
        userAttr: uid
        groupAttr: memberUid
        nameAttr: cn

web:
  http: 0.0.0.0:5556

oauth2:
  skipApprovalScreen: true
  alwaysShowLoginScreen: true

staticClients:
  - id: convex-client
    redirectURIs:
      - "http://localhost:3000/api/auth/callback/dex"
    name: "Example App"
    secret: example-secret